### PR TITLE
Updated Sayonika logo in README.md

### PR DESCRIPTION
**Pull request by nxahjs**
Title says all 🙂

### CODE REVIEW

**Comment by Ovyerus** [comment]
Is the logo properly centered? Looks off.

**Comment by nxahjs** [comment]
well, i cba to do the maths for it so uhh it may be off a little smidge

**Comment by Ovyerus** [comment]
Whatever you're using should have an align tool.

**Comment by nxahjs** [comment]
not that i know of

**Comment by Ovyerus** [comment]
What program?

**Review by sr229 — CHANGES_REQUESTED** [review]
Glyphs not in true center, please fix this first.

**Comment by sr229** [comment]
Closing this to be cherry picked later.

Reached expiration date.

**Pull request closed without merging**
